version: '3.9'

services:
  loginvalidation:
    container_name: loginvalidation
    image: loginvalidation
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - mysqlnet
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    restart: always

  mysqldb-loginvalidation:
    container_name: mysqldb-loginvalidation
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ####
      MYSQL_DATABASE: ####
      MYSQL_USER: ####
      MYSQL_PASSWORD: ####
    ports:
      - 3309:3306
    networks:
      - mysqlnet
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:

networks:
  mysqlnet: